#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fm-common
Version  : 1
Release  : 1
URL      : https://github.com/openstack/stx-fault/archive/master.zip
Source0  : https://github.com/openstack/stx-fault/archive/master.zip
Summary  : CGTS Platform SNMP extension Package
Group    : Development/Tools
License  : Apache-2.0 windriver
Requires: fm-common-bin
Requires: fm-common-python3
Requires: fm-common-lib
Requires: fm-common-python
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : postgresql-dev
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : util-linux-dev
BuildRequires : virtualenv
Patch1: 0001-license-fixup.patch

%description
Titanium Cloud platform Fault Management Client Library that provides APIs for
applications to raise/clear/update active alarms.

%package bin
Summary: bin components for the fm-common package.
Group: Binaries

%description bin
bin components for the fm-common package.


%package dev
Summary: dev components for the fm-common package.
Group: Development
Requires: fm-common-lib
Requires: fm-common-bin
Provides: fm-common-devel

%description dev
dev components for the fm-common package.


%package lib
Summary: lib components for the fm-common package.
Group: Libraries

%description lib
lib components for the fm-common package.


%package python
Summary: python components for the fm-common package.
Group: Default
Requires: fm-common-python3

%description python
python components for the fm-common package.


%package python3
Summary: python3 components for the fm-common package.
Group: Default
Requires: python3-core

%description python3
python3 components for the fm-common package.


%prep
%setup -q -n stx-fault-master
%patch1 -p1

%build
## build_prepend content
version=%{version}
MAJOR=${version%%.*}
MINOR=${version##*.}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536193584
pushd fm-common/sources
make  %{?_smp_mflags} MAJOR=${version%%.*} MINOR=${version##*.} EXTRACCFLAGS="$CXXFLAGS"
popd

%install
export SOURCE_DATE_EPOCH=1536193584
rm -rf %{buildroot}
pushd fm-common/sources
echo "Empty"
popd
## install_append content
pushd fm-common/sources
python3 -tt setup.py build -b py3 install --root=%{buildroot}
version=%{version}
MAJOR=${version%%.*}
MINOR=${version##*.}
make DEST_DIR=%{buildroot} BIN_DIR=%{_bindir} LIB_DIR=%{_libdir} INC_DIR=%{_includedir} MAJOR=$MAJOR MINOR=$MINOR install_non_bb
install -d %{buildroot}/usr/bin
install -m 755 fm_db_sync_event_suppression.py %{buildroot}/usr/bin/fm_db_sync_event_suppression.py
install -m 644 -p -D fmConfig.h %{buildroot}%{_includedir}/fmConfig.h
install -m 644 -p -D fmLog.h %{buildroot}%{_includedir}/fmLog.h
popd
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fmClientCli
/usr/bin/fm_db_sync_event_suppression.py

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libfmcommon.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfmcommon.so.1
/usr/lib64/libfmcommon.so.1.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
